eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZhangLujie4/config-repo.git
          basedir: F:/SpringCloud_sell/config/basedir
          username: 949941475@qq.com
          password: lvlan4shuilu
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"